#!/bin/bash

dist=$(tr -s ' \011' '\012' < /etc/issue | head -n 1)

check_arch=$(uname -m)

echo "[$green+$txtrst] Distribution Name: $dist"

if [ $Operating_System == "CentOS" ]
then
    echo "CentOS";
    # Do this

elif [ $Operating_System == "Ubuntu" ]
then
    echo "Ubuntu";
    # Do that

elif [ $Operatting_System == "Debian" ]
then
    echo "Debian";
    # Do this

else
    echo "Unsupported Operating System";
fi
